//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch regshot.rc
//
#define IDD_DIALOG1                     100
#define IDD_DIALOG_OPT_COMMON           101
#define IDD_DIALOG_OPT_SKIPREG          102
#define IDD_DIALOG_OPT_SKIPDIR          103
#define IDI_MAINICON                    111
#define IDR_MENU1                       123
#define IDI_ICON_GREEN                  124
#define IDI_ICON_RED                    125
#define IDR_MENU_CONTEXT_SKIPLIST       128
#define IDD_DIALOG_OPT_SKIPFILE         129
#define IDD_DIALOG_OPT_SCANDIR          130
#define IDD_DIALOG_TV_REGS              131
#define IDD_DIALOG_OPT_COMMON_2         132
#define IDB_TREE                        133
#define IDD_DIALOG_OPT_SKIPREG1         133
#define IDD_DIALOG_OPT_SCANREG          133
#define IDB_FILE                        135
#define IDB_FOLDER_CLOSED               136
#define IDB_BITMAP1                     137
#define IDB_FOLDER_OPEN                 137
#define ID_BASE                         1000
#define IDC_1STSHOT                     1003
#define IDC_2NDSHOT                     1004
#define IDC_COMPARE                     1005
#define IDC_CLEARALL                    1006
#define IDC_QUIT                        1007
#define IDC_ABOUT                       1008
#define IDC_MONITOR                     1009
#define IDC_STATICSAVEFORMAT            1010
#define IDC_STATICOUTPUTPATH            1011
#define IDC_STATICADDCOMMENT            1012
#define IDC_CHECK_BAT                   1013
#define IDC_CHECK_HTML                  1014
#define IDC_CHECK_UNL                   1015
#define IDC_STATICSERVICE               1016
#define IDC_STATICRING3                 1017
#define IDC_SETMASK                     1018
#define IDC_CHECKONTOP                  1019
#define IDC_CHECKPAUSE                  1020
#define IDC_CLEAR2                      1021
#define IDM_SAVE                        1022
#define IDC_CANCEL2                     1023
#define IDC_PROGBAR                     1024
#define IDC_EDITCOMMENT                 1025
#define IDC_EDITPATH                    1026
#define IDC_EDITDIR                     1027
#define IDC_TEXTCOUNT1                  1028
#define IDC_TEXTCOUNT2                  1029
#define IDC_TEXTCOUNT3                  1030
#define IDC_BROWSE1                     1031
#define IDC_BROWSE2                     1032
#define IDC_COMBOLANGUAGE               1033
#define IDC_RegOpenKey                  1034
#define IDC_TEXT_REMARK                 1034
#define IDC_RegCloseKey                 1035
#define IDC_RegCreateKey                1036
#define IDC_RegDeleteKey                1037
#define IDC_RegSetValue                 1038
#define IDC_RegSetValueEx               1039
#define IDC_RegQueryValue               1040
#define IDC_RegQueryValueEx             1041
#define IDC_RegDeleteValue              1042
#define IDC_RegEnumKey                  1043
#define IDC_RegEnumValue                1044
#define IDC_RegFlushKey                 1045
#define IDC_EDITRING3                   1046
#define IDC_LIST_SKIP                   1047
#define IDM_SHOTONLY                    1048
#define IDM_SHOTSAVE                    1049
#define IDM_LOAD                        1050
#define IDM_BREAK                       1051
#define IDM_CLEARALL                    1052
#define IDM_CLEAR                       1053
#define IDM_INFO                        1054
#define IDM_SWAP                        1055
#define IDM_COMPARE                     1056
#define IDM_COMPAREOUTPUT               1057
#define IDM_OUTPUT                      1058
#define IDC_CHECK_HKLM                  1059
#define IDC_CHECK_HKU                   1060
#define IDC_CHECK_HKCU                  1061
#define IDC_CHECKDIR                    1062
#define IDC_EDITTITLE                   1063
#define IDM_SHOTCOMPAREOUTPUT           1064
#define IDC_CHECK_REGDEL                1065
#define IDC_CHECK_REGINS                1066
#define IDC_STATIC_TITLE                1067
#define IDC_CHECK_ISSDEL                1067
#define IDC_STATIC_REGS                 1068
#define IDC_CHECK_ISSINS                1068
#define IDC_STATIC_DIRS                 1069
#define IDC_CHECK_ISSOUTPUTFOLDER       1069
#define IDC_TEXTCOUNT4                  1070
#define IDC_CHECK_ISSEDITOR             1070
#define IDC_CHECK_DELSHOTS              1071
#define IDC_CHECK_SAVEINI               1072
#define IDC_CHECK_DELSHOTS2             1072
#define IDC_CHECK_OPENEDITOR            1072
#define IDC_CHECK_DEFAULTS              1073
#define IDC_CHECK_AUTOCOMPARE           1074
#define IDC_CHECK_ONLYADDED             1075
#define IDC_SAVE_INI                    1076
#define IDC_LOAD_INI                    1077
#define IDC_STATIC_BMP                  1078
#define IDC_CHECK_NOVALS                1079
#define IDC_CHECK_ENVIRONMENT           1080
#define IDC_PROP_DIRS                   1081
#define IDC_CHECK_OPT_STOREONQUIT       1081
#define IDC_PROP_REGS                   1082
#define IDC_CHECK_OPT_LONGREGKEYS       1082
#define IDC_CHECK_UNLORDER              1083
#define IDC_CHECK_OPT_SEPARATEOBJECTS   1083
#define IDC_CHECK_OPT_DONTDISPLAYINFO   1084
#define IDC_CHECK_NOFILTERS             1084
#define IDC_CHECK_OPT_DONTDISPLAYRESULT 1085
#define IDC_OUTPUT_RESET                1085
#define IDC_STATIC_REG                  1086
#define IDC_PROP_CLEAR2                 1086
#define IDC_STATIC_INF                  1087
#define IDC_PROP_CLEAR1                 1087
#define IDC_STATIC_COMMON               1088
#define IDC_CHECK_OPT_SAVEINI           1089
#define IDC_CHECK_OPT_STOREONLYUNCOMP   1090
#define IDC_BUTTON_ADDSKIP              1091
#define IDC_CHECK_OPT_NOFILTERS         1091
#define IDC_EDIT_ADDSKIPSTRING          1092
#define IDC_CHECK_OPT_READONLY          1092
#define IDC_BUTTON_SAVESKIP2INI         1093
#define IDC_STATIC_LANGUAGESELECTIONTOINI 1093
#define IDC_CHECK_OPT_NONEMPTY          1094
#define IDC_CHECK_OPT_SIDFILTERS        1095
#define IDC_EDIT_ADDSKIPFILESTRING      1096
#define IDC_STATIC_SKIPFILE_COMMENT     1097
#define IDC_BUTTON_ADDSKIPFILE          1098
#define IDC_BUTTON_ADDSKIPFILE2INI      1099
#define IDC_BROWSE_FILESKIP             1100
#define IDC_COMBO_MAINCP                1101
#define IDC_CHECK_TXT                   1102
#define IDC_COMMON_EDIT_EDITOR          1103
#define IDC_EDIT_OUTPUTLINES            1103
#define IDC_COMMON_BROWSEEDITOR         1104
#define IDC_STATIC_EDITOR               1105
#define IDC_REGEDIT5                    1106
#define IDC_REGEDIT4                    1107
#define IDC_STATIC_REGFORMAT            1108
#define IDC_TREE_SKIPS                  1109
#define IDC_COMMON_EDIT_ISSOUTPUT       1109
#define IDC_CHECK_RESULT                1110
#define IDC_COMMON_BROWSEISSOUTPUT      1110
#define IDC_CHECK_OPT_ENVIRONMENT       1111
#define IDC_CHECK_RESETADHOC            1111
#define IDC_COMMON_EDIT_ISSEDITOR       1112
#define IDC_STATIC_SKIP_COMMENT2        1113
#define IDC_COMMON_BROWSEISSEDITOR      1113
#define IDC_STATIC_SKIP_COMMENT3        1114
#define IDC_STATIC_NSI                  1115
#define IDC_CHECK_NSIDEL                1116
#define IDC_CHECK_NSIINS                1117
#define IDC_CHECK_NSIOUTPUTFOLDER       1118
#define IDC_COMMON_EDIT_NSIOUTPUT       1119
#define IDC_COMMON_BROWSENSIOUTPUT      1120
#define IDC_CHECK_NSIEDITOR             1121
#define IDC_COMMON_EDIT_NSIEDITOR       1122
#define IDC_COMMON_BROWSENSIEDITOR      1123
#define IDM_OUTPUT_FS                   1124
#define IDM_OUTPUT_REG                  1125
#define IDC_CHECK1                      1126
#define IDC_CHECK_SUPPRESS              1126
#define ID_FILE                         40007
#define ID_HELP_ABOUT                   40010
#define ID_FILE_QUIT                    40011
#define ID_FILE_OPEN                    40012
#define ID_1_SHOT                       40013
#define ID_1_SHOTANDSAVE                40014
#define ID_1_LOAD                       40015
#define ID_1_SAVE                       40016
#define ID_1_CLEAR                      40017
#define ID_1_INFO                       40018
#define ID_1_SWAP                       40019
#define ID_2_SHOT                       40020
#define ID_2_SHOT40021                  40021
#define ID_2_SHOTANDSAVE                40022
#define ID_2_LOAD                       40023
#define ID_2_SAVE                       40024
#define ID_2_CLEAR                      40025
#define ID_2_INFO                       40026
#define ID_2_SWAP                       40027
#define ID_COMPARE_COMPARE              40028
#define ID_COMPARE_COMPAREANDOUTPUT     40029
#define ID_COMPARE_OUTPUT               40030
#define ID_COMPARE_CLEAR                40031
#define ID_COMPARE_INFO                 40032
#define ID_FILE_CLEARALL                40033
#define ID_FILE_OPTIONS                 40034
#define ID_2_SHOTCOMPAREOUTPUT          40035
#define ID_SETTINGS                     40036
#define ID_CONTEXTMENU_DELETE           40037
#define ID_CONTEXTMENU_CHECKALL         40038
#define ID_CONTEXTMENU_UNCHECKALL       40039
#define ID_CONTEXTMENU_INVERTCHECKS     40040
#define ID_COMPARE_OUTPUT40041          40041
#define ID_COMPARE_OUTPUT40042          40042
#define ID_COMPARE_OUTPUT_FS            40043
#define ID_COMPARE_OUTPUT_REG           40044
#define IDC_STATIC_SKIPDIR_COMMENT      -1
#define IDC_STATIC_SKIP_COMMENT         -1
#define IDC_STATIC_UNL                  -1
#define IDC_STATIC_OUTPUTLINES          -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40045
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
