#ifndef REGSHOT_REVISION_H
#define REGSHOT_REVISION_H

#define REGSHOT_REVISION_NUM          0
#define REGSHOT_REVISION_NUM_SUFFIX   Unknown
#define REGSHOT_REVISION_MOD          1

#endif // REGSHOT_REVISION_H
